---
region: 'eu-west-2'

component: 'test'
deployment_identifier: "%{hiera('seed')}"

domain_name: "infrablocks-elasticache-redis-%{hiera('seed')}.example"

allowed_cidrs:
  - '0.0.0.0/0'

vpc_cidr: '10.1.0.0/16'
availability_zones:
  - "eu-west-2a"
  - "eu-west-2b"

node_count: 2
node_type: 'cache.t2.micro'

auth_token: 'APVjubqGt74ruXVwfLQJTFjVH6J7T3eGkgJJcQRTFPz3urf6EGkYo7a2xAGUndp4'
